# Generated by Django 5.2.6 on 2025-09-27 14:14

import django.db.models.deletion
import encrypted_model_fields.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Название биржи')),
                ('is_available', models.BooleanField(db_index=True, default=True, editable=False, help_text='Заполняется и изменяется автоматически (health-check, статусы API).', verbose_name='Биржа доступна')),
                ('can_receive', models.BooleanField(default=True, verbose_name='Приём средств')),
                ('can_send', models.BooleanField(default=True, verbose_name='Отдача средств')),
                ('stablecoin', models.CharField(default='USDT', help_text='Стейблкоин для расчётов, например: USDT.', max_length=20, verbose_name='Рабочий стейблкоин')),
                ('spot_taker_fee', models.DecimalField(decimal_places=4, default=Decimal('0.1'), help_text='Комиссия тейкера на споте', max_digits=7, verbose_name='Спот: тейкер, %')),
                ('spot_maker_fee', models.DecimalField(decimal_places=4, default=Decimal('0.1'), help_text='комиссия мейкера на споте', max_digits=7, verbose_name='Спот: мейкер, %')),
                ('futures_taker_fee', models.DecimalField(decimal_places=4, default=Decimal('0.1'), help_text='Комиссия тейкера на фьючерсах', max_digits=7, verbose_name='Фьючерсы: тейкер, %')),
                ('futures_maker_fee', models.DecimalField(decimal_places=4, default=Decimal('0.1'), help_text='Комиссия мейкера на фьючерсах.', max_digits=7, verbose_name='Фьючерсы: мейкер, %')),
                ('show_prices_on_home', models.BooleanField(db_index=True, default=False, verbose_name='Показывать цены на главной')),
            ],
            options={
                'verbose_name': 'Биржа',
                'verbose_name_plural': 'Биржи',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='default', help_text='Например: main, trading, withdraw-only и т.п.', max_length=64, verbose_name='Метка ключей')),
                ('api_key', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True, verbose_name='API Key')),
                ('api_secret', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True, verbose_name='API Secret')),
                ('api_passphrase', encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='Иногда требуется (например, на некоторых биржах).', null=True, verbose_name='API Passphrase')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Включён')),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='app_market.exchange', verbose_name='Биржа')),
            ],
            options={
                'verbose_name': 'API ключи биржи',
                'verbose_name_plural': 'API ключи бирж',
                'constraints': [models.UniqueConstraint(fields=('exchange', 'label'), name='uniq_exchange_apikey_label')],
            },
        ),
    ]
