# Generated by Django 5.2.6 on 2025-10-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='description',
            field=models.TextField(blank=True, default='небольшой комментарий о провайдере', null=True, verbose_name='Описание '),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='provider',
            field=models.CharField(choices=[('KUCOIN', 'KuCoin'), ('WHITEBIT', 'WhiteBIT'), ('BYBIT', 'ByBit'), ('HTX', 'HTX'), ('MEXC', 'MEXC'), ('RAPIRA', 'Rapira'), ('BINANCE', 'Binance'), ('COINBASE_EXCHANGE', 'Coinbase Exchange'), ('UPBIT', 'Upbit'), ('BITSTAMP', 'Bitstamp'), ('BINGX', 'BingX'), ('BITFINEX', 'Bitfinex'), ('GATEIO', 'Gate.io'), ('BITGET', 'Bitget'), ('OKX', 'OKX'), ('GEMINI', 'Gemini'), ('LBANK', 'LBank'), ('UNISWAP', 'Uniswap'), ('PANCAKESWAP', 'PancakeSwap'), ('PAYPAL', 'PayPal'), ('ADVCASH', 'Advanced Cash'), ('FIREKASSA', 'FireKassa'), ('APIRONE', 'Apirone'), ('CHANGENOW', 'ChangeNOW'), ('CHANGELLY', 'Changelly'), ('FIXEDFLOAT', 'ff.io'), ('QUICKEX', 'Quickex'), ('ALFABIT', 'Alfabit'), ('WESTWALLET', 'WestWallet'), ('TRUSTWALLET', 'Trust Wallet'), ('TRONWALLET', 'Tron Wallet'), ('ANTARCTICWALLET', 'Antarctic Wallet'), ('TELEGRAM_WALLET', 'Telegram Wallet'), ('BTC_NODE', 'BTC Node'), ('XMR_NODE', 'XMR Node'), ('USDT_NODE', 'USDT Node'), ('USDC_NODE', 'USDC Node'), ('DASH_NODE', 'DASH Node'), ('SBERBANK', 'Сбербанк'), ('TBANK', 'ТБанк'), ('ALFABANK', 'Альфабанк'), ('VTB', 'ВТБ банк'), ('CASH', 'Наличные'), ('TWELVEDATA', 'Twelve Data'), ('OpExRate', 'Open Exchange Rates')], db_index=True, default='CASH', max_length=32, unique=True, verbose_name='Название'),
        ),
    ]
