# Generated by Django 5.2.6 on 2025-09-27 14:29

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeapikey',
            name='api_key_view',
            field=models.CharField(blank=True, default='', editable=False, help_text='Маскированный вид ключа для отображения.', max_length=272, verbose_name='API Key (вид)'),
        ),
        migrations.AddField(
            model_name='exchangeapikey',
            name='api_passphrase_view',
            field=models.CharField(blank=True, default='', editable=False, max_length=272, verbose_name='API Passphrase (вид)'),
        ),
        migrations.AddField(
            model_name='exchangeapikey',
            name='api_secret_view',
            field=models.CharField(blank=True, default='', editable=False, max_length=272, verbose_name='API Secret (вид)'),
        ),
        migrations.AlterField(
            model_name='exchangeapikey',
            name='api_passphrase',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='Иногда требуется на некоторых биржах.', null=True, verbose_name='API Passphrase'),
        ),
    ]
