# Generated by Django 5.2.6 on 2025-10-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='stats_history',
            field=models.JSONField(blank=True, default=list, help_text='Хронологические снимки: кошелёк/рынок, распределение правых валют, самый популярный стейбл.', verbose_name='Статистика провайдера (история)'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='stablecoin',
            field=models.CharField(default='USDT, USDC', help_text='Стейблкоины для расчётов, например: USDT.', max_length=40, verbose_name='Рабочий стейблкоин'),
        ),
    ]
