# Generated by Django 5.2.6 on 2025-09-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_market', '0002_exchangeapikey_api_key_view_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='exchange_kind',
            field=models.CharField(choices=[('CEX', 'Классическая биржа'), ('DEX', 'Децентрализованная биржа'), ('PSP', 'Платёжная система'), ('MANUAL', 'Ручной обмен')], db_index=True, default='CEX', help_text='CEX / DEX / PSP / MANUAL', max_length=10, verbose_name='Тип биржи'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='name',
            field=models.CharField(default='Manual', max_length=120, unique=True, verbose_name='Название биржи'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='show_prices_on_home',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Цены на главную'),
        ),
        migrations.AlterField(
            model_name='exchangeapikey',
            name='api_key_view',
            field=models.CharField(blank=True, default='', editable=False, max_length=272, verbose_name='API Key (вид)'),
        ),
    ]
