# Generated by Django 5.2.6 on 2025-10-09 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_market', '0002_alter_exchange_exchange_kind_alter_exchange_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangeasset',
            name='asset_kind',
            field=models.CharField(choices=[('CRYPTO', 'Крипта'), ('FIAT', 'Фиат'), ('PSP_MONEY', 'Платёжка'), ('CASH', 'Наличные'), ('NOTDEFINED', 'Не определён')], db_index=True, default='CRYPTO', max_length=16, verbose_name='Тип актива'),
        ),
    ]
