# Generated by Django 5.2.6 on 2025-10-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_market', '0002_exchange_stats_history_alter_exchange_stablecoin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='stablecoin',
            field=models.CharField(blank=True, default='USDT', help_text='Стейблкоины для расчётов. Заполняются автоматически.', max_length=40, null=True, verbose_name='Рабочий стейблкоин'),
        ),
    ]
