# Generated by Django 5.2.6 on 2025-10-16 15:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_market', '0003_alter_exchange_stablecoin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricel1',
            options={'ordering': ['-ts_src', '-id'], 'verbose_name': 'L1-котировка (bid/ask)', 'verbose_name_plural': 'L1-котировки (bid/ask)'},
        ),
        migrations.RemoveIndex(
            model_name='pricel1',
            name='idx_price_l1_src',
        ),
        migrations.RemoveIndex(
            model_name='pricel1',
            name='idx_price_l1_venue',
        ),
        migrations.RemoveIndex(
            model_name='pricel1',
            name='idx_price_l1_status',
        ),
        migrations.RemoveField(
            model_name='pricel1',
            name='base_asset',
        ),
        migrations.RemoveField(
            model_name='pricel1',
            name='quality_note',
        ),
        migrations.RemoveField(
            model_name='pricel1',
            name='quote_asset',
        ),
        migrations.RemoveField(
            model_name='pricel1',
            name='status',
        ),
        migrations.RemoveField(
            model_name='pricel1',
            name='venue_type',
        ),
        migrations.AddField(
            model_name='pricel1',
            name='fee_source',
            field=models.CharField(choices=[('PUBLIC', 'Публичный API'), ('PRIVATE', 'Приватный API'), ('PAIR', 'Переписано из пары/инструмента'), ('UNKNOWN', 'Неизвестно')], default='UNKNOWN', max_length=16, verbose_name='Источник комиссий'),
        ),
        migrations.AlterField(
            model_name='pricel1',
            name='extras',
            field=models.JSONField(blank=True, default=dict, help_text='Сырые поля источника: best sizes, quoteId, pool reserves и пр.', verbose_name='Доп. данные'),
        ),
        migrations.AlterField(
            model_name='pricel1',
            name='fee_maker_bps',
            field=models.PositiveIntegerField(default=0, help_text='Для лимитных стратегий; может быть ноль, если не используем.', verbose_name='Maker комиссия, bps'),
        ),
        migrations.AlterField(
            model_name='pricel1',
            name='fee_taker_bps',
            field=models.PositiveIntegerField(default=0, help_text='Если приватные комиссии доступны — сохраняем их, они важнее публичных.', verbose_name='Taker комиссия, bps'),
        ),
        migrations.AlterField(
            model_name='pricel1',
            name='provider',
            field=models.ForeignKey(help_text='Связь на Exchange (ПЛ). Вид площадки см. provider.exchange_kind.', on_delete=django.db.models.deletion.PROTECT, related_name='prices_l1', to='app_market.exchange', verbose_name='Поставщик ликвидности'),
        ),
        migrations.AlterField(
            model_name='pricel1',
            name='seq',
            field=models.BigIntegerField(blank=True, help_text='Для WS/стримов (last_update_id, trade_id и т.п.), если есть.', null=True, verbose_name='Последовательность/offset'),
        ),
        migrations.AlterField(
            model_name='pricel1',
            name='src_base_code',
            field=models.CharField(db_index=True, help_text='Ticker/contract базового актива у провайдера.', max_length=32, verbose_name='Код базового у ПЛ'),
        ),
        migrations.AlterField(
            model_name='pricel1',
            name='src_quote_code',
            field=models.CharField(db_index=True, help_text='Ticker/contract котируемого актива у провайдера.', max_length=32, verbose_name='Код котируемого у ПЛ'),
        ),
        migrations.AlterField(
            model_name='pricel1',
            name='src_symbol',
            field=models.CharField(db_index=True, help_text='Напр. BTCUSDT, BTC_USDT, ETH-BTC и т.п.', max_length=64, verbose_name='Исходный символ у ПЛ'),
        ),
        migrations.AlterField(
            model_name='pricel1',
            name='ts_ingest',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Когда наша система приняла/нормализовала котировку.', verbose_name='Время приёма'),
        ),
        migrations.AlterField(
            model_name='pricel1',
            name='ts_src',
            field=models.DateTimeField(db_index=True, help_text='Timestamp от ПЛ (сервер источника); если не приходит — подставляем ingest.', verbose_name='Время у источника'),
        ),
        migrations.AddIndex(
            model_name='pricel1',
            index=models.Index(fields=['provider', 'src_base_code', 'src_quote_code', '-ts_src'], name='idx_l1_prov_pair_src'),
        ),
        migrations.AddIndex(
            model_name='pricel1',
            index=models.Index(fields=['src_symbol', '-ts_src'], name='idx_l1_symbol_src'),
        ),
        migrations.AddIndex(
            model_name='pricel1',
            index=models.Index(fields=['-ts_ingest'], name='idx_l1_ingest_desc'),
        ),
    ]
