# Generated by Django 5.2.6 on 2025-10-09 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_market', '0003_alter_exchangeasset_asset_kind'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangeasset',
            name='last_synced_at',
        ),
    ]
