# Generated by Django 5.2.6 on 2025-09-27 16:03

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_market', '0003_exchange_exchange_kind_alter_exchange_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='exchange_kind',
            field=models.CharField(choices=[('CEX', 'Классическая биржа (CEX)'), ('DEX', 'Децентрализованная биржа (DEX)'), ('PSP', 'Платёжная система'), ('MANUAL', 'Ручной обмен')], db_index=True, default='CEX', help_text='CEX / DEX / PSP / MANUAL', max_length=10, verbose_name='Тип биржи'),
        ),
        migrations.CreateModel(
            name='PaymentProviderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment', models.CharField(choices=[('LIVE', 'Прод (LIVE)'), ('SANDBOX', 'Песочница (SANDBOX)')], db_index=True, default='LIVE', help_text='LIVE или SANDBOX.', max_length=8, verbose_name='Окружение')),
                ('merchant_id', models.CharField(blank=True, default='', max_length=128, verbose_name='Merchant ID')),
                ('account_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Учётный email в PSP')),
                ('api_base_url', models.URLField(blank=True, default='', verbose_name='API Base URL')),
                ('dashboard_url', models.URLField(blank=True, default='', verbose_name='URL кабинета')),
                ('settlement_currency', models.CharField(default='USD', help_text='Например: USD.', max_length=10, verbose_name='Валюта расчёта')),
                ('fee_deposit_percent', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=7, verbose_name='Комиссия на приём, %')),
                ('fee_deposit_fixed', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='В валюте расчёта.', max_digits=12, verbose_name='Комиссия на приём, фикс')),
                ('fee_payout_percent', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=7, verbose_name='Комиссия на выплату, %')),
                ('fee_payout_fixed', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='В валюте расчёта.', max_digits=12, verbose_name='Комиссия на выплату, фикс')),
                ('min_deposit', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='Мин. приём')),
                ('max_deposit', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='Макс. приём')),
                ('min_payout', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='Мин. выплата')),
                ('max_payout', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='Макс. выплата')),
                ('webhook_endpoint', models.URLField(blank=True, default='', verbose_name='Webhook endpoint')),
                ('idempotency_window_sec', models.PositiveIntegerField(default=300, help_text='Защита от повторной обработки (по умолчанию 5 минут).', verbose_name='Окно идемпотентности, сек')),
                ('exchange', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='psp_profile', to='app_market.exchange', verbose_name='Провайдер (Exchange)')),
            ],
            options={
                'verbose_name': 'Профиль платёжного провайдера',
                'verbose_name_plural': 'Профили платёжных провайдеров',
            },
        ),
    ]
