# Generated by Django 5.2.6 on 2025-09-29 10:04

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_market', '0004_alter_exchange_exchange_kind_paymentproviderprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchange',
            options={'ordering': ['provider'], 'verbose_name': 'Поставщик ликвидности', 'verbose_name_plural': 'Поставщики ликвидности'},
        ),
        migrations.AlterModelOptions(
            name='paymentproviderprofile',
            options={'verbose_name': 'Платёжная система', 'verbose_name_plural': 'Платёжные системы'},
        ),
        migrations.RemoveField(
            model_name='exchange',
            name='name',
        ),
        migrations.AddField(
            model_name='exchange',
            name='fee_deposit_fixed',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Фикс. комиссия на ввод в базовой валюте расчёта.', max_digits=12, verbose_name='Ввод: фикс'),
        ),
        migrations.AddField(
            model_name='exchange',
            name='fee_deposit_max',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Неотрицательная. Оставьте пустым для безлимитного верха.', max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Ввод: макс. комиссия'),
        ),
        migrations.AddField(
            model_name='exchange',
            name='fee_deposit_min',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), help_text='Неотрицательная. Применяется после расчёта % + фикс.', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Ввод: мин. комиссия'),
        ),
        migrations.AddField(
            model_name='exchange',
            name='fee_deposit_percent',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Процент комиссии на ввод (может быть 0).', max_digits=7, verbose_name='Ввод: %'),
        ),
        migrations.AddField(
            model_name='exchange',
            name='fee_withdraw_fixed',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Фикс. комиссия на вывод в базовой валюте расчёта.', max_digits=12, verbose_name='Вывод: фикс'),
        ),
        migrations.AddField(
            model_name='exchange',
            name='fee_withdraw_max',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Неотрицательная. Оставьте пустым для безлимитного верха.', max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Вывод: макс. комиссия'),
        ),
        migrations.AddField(
            model_name='exchange',
            name='fee_withdraw_min',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), help_text='Неотрицательная. Применяется после расчёта % + фикс.', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Вывод: мин. комиссия'),
        ),
        migrations.AddField(
            model_name='exchange',
            name='fee_withdraw_percent',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Процент комиссии на вывод (может быть 0).', max_digits=7, verbose_name='Вывод: %'),
        ),
        migrations.AddField(
            model_name='exchange',
            name='provider',
            field=models.CharField(choices=[('KUCOIN', 'KuCoin'), ('WHITEBIT', 'WhiteBIT'), ('RAPIRA', 'Rapira'), ('MEXC', 'MEXC'), ('MANUAL', 'Ручной обмен'), ('PAYPAL', 'PayPal'), ('ADVCASH', 'Advanced Cash')], db_index=True, default=1, help_text='Выберите из списка: биржи, ручной обмен, платёжные системы.', max_length=20, unique=True, verbose_name='Поставщик ликвидности'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exchange',
            name='exchange_kind',
            field=models.CharField(choices=[('CEX', 'Классическая биржа (CEX)'), ('DEX', 'Децентрализованная биржа (DEX)'), ('PSP', 'Платёжная система'), ('MANUAL', 'Ручной обмен')], db_index=True, default='CEX', help_text='CEX / DEX / PSP / MANUAL', max_length=10, verbose_name='Тип поставщика'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='futures_maker_fee',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.1'), help_text='Может быть отрицательной.', max_digits=7, verbose_name='Фьючерсы: мейкер, %'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='futures_taker_fee',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.1'), help_text='Может быть отрицательной.', max_digits=7, verbose_name='Фьючерсы: тейкер, %'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='is_available',
            field=models.BooleanField(db_index=True, default=True, editable=False, help_text='Изменяется автоматически (health-check, статусы API).', verbose_name='Доступен'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='show_prices_on_home',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Цены на главной'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='spot_maker_fee',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.1'), help_text='Может быть отрицательной.', max_digits=7, verbose_name='Спот: мейкер, %'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='spot_taker_fee',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.1'), help_text='Может быть отрицательной.', max_digits=7, verbose_name='Спот: тейкер, %'),
        ),
    ]
