# Generated by Django 5.2.6 on 2025-10-18 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_market', '0004_alter_pricel1_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='stablecoin',
            field=models.CharField(blank=True, default='', help_text='Стейблкоины для расчётов. Заполняются автоматически.', max_length=40, null=True, verbose_name='Рабочий стейблкоин'),
        ),
    ]
