# Generated by Django 5.2.6 on 2025-10-12 09:36

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_market', '0004_remove_exchangeasset_last_synced_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='exchange_kind',
            field=models.CharField(choices=[('CEX', 'Классическая биржа (CEX)'), ('DEX', 'Децентрализованная биржа (DEX)'), ('PSP', 'Платёжная система (PSP)'), ('WALLET', 'Кошелёк'), ('NODE', 'Нода'), ('EXCHANGER', 'Обменники'), ('BANK', 'Банк'), ('CASH', 'Наличные')], db_index=True, default='CEX', editable=False, help_text='Устанавливается автоматически', max_length=10, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='fee_deposit_min',
            field=models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=28, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Ввод: мин. комиссия'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='provider',
            field=models.CharField(choices=[('KUCOIN', 'KuCoin'), ('WHITEBIT', 'WhiteBIT'), ('BYBIT', 'ByBit'), ('HTX', 'HTX'), ('MEXC', 'MEXC'), ('RAPIRA', 'Rapira'), ('BINANCE', 'Binance'), ('COINBASE_EXCHANGE', 'Coinbase Exchange'), ('UPBIT', 'Upbit'), ('BITSTAMP', 'Bitstamp'), ('BINGX', 'BingX'), ('BITFINEX', 'Bitfinex'), ('GATEIO', 'Gate.io'), ('BITGET', 'Bitget'), ('OKX', 'OKX'), ('GEMINI', 'Gemini'), ('LBANK', 'LBank'), ('UNISWAP', 'Uniswap'), ('PANCAKESWAP', 'PancakeSwap'), ('PAYPAL', 'PayPal'), ('ADVCASH', 'Advanced Cash'), ('FIREKASSA', 'FireKassa'), ('APIRONE', 'Apirone'), ('CHANGENOW', 'ChangeNOW'), ('CHANGELLY', 'Changelly'), ('FIXEDFLOAT', 'ff.io'), ('QUICKEX', 'Quickex'), ('ALFABIT', 'Alfabit'), ('WESTWALLET', 'WestWallet'), ('TRUSTWALLET', 'Trust Wallet'), ('TRONWALLET', 'Tron Wallet'), ('ANTARCTICWALLET', 'Antarctic Wallet'), ('TELEGRAM_WALLET', 'Telegram Wallet'), ('BTC_NODE', 'BTC Node'), ('XMR_NODE', 'XMR Node'), ('USDT_NODE', 'USDT Node'), ('USDC_NODE', 'USDC Node'), ('DASH_NODE', 'DASH Node'), ('SBERBANK', 'Сбербанк'), ('TBANK', 'ТБанк'), ('ALFABANK', 'Альфабанк'), ('VTB', 'ВТБ банк'), ('CASH', 'Cash')], db_index=True, default='CASH', max_length=32, unique=True, verbose_name='Название'),
        ),
    ]
