# Generated by Django 5.2.6 on 2025-09-29 10:27

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_market', '0005_alter_exchange_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='webhook_endpoint',
            field=models.URLField(blank=True, default='', verbose_name='Webhook endpoint'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='fee_deposit_fixed',
            field=models.DecimalField(decimal_places=5, default=Decimal('0'), max_digits=12, verbose_name='Ввод: фикс'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='fee_deposit_max',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Ввод: макс. комиссия'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='fee_deposit_min',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Ввод: мин. комиссия'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='fee_deposit_percent',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=7, verbose_name='Ввод: %'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='fee_withdraw_fixed',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18, verbose_name='Вывод: фикс'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='fee_withdraw_max',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Вывод: макс. комиссия'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='fee_withdraw_min',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Вывод: мин. комиссия'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='fee_withdraw_percent',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18, verbose_name='Вывод: %'),
        ),
    ]
