# Generated by Django 5.2.6 on 2025-10-18 15:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_market', '0005_alter_exchange_stablecoin'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricel1',
            name='dv',
            field=models.DecimalField(decimal_places=10, default=0, help_text='Дневная волатильность. По умолчанию 0.', max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='DV (дневная волатильность)'),
        ),
        migrations.AddField(
            model_name='pricel1',
            name='hv',
            field=models.DecimalField(decimal_places=10, default=0, help_text='Часовая волатильность. По умолчанию 0.', max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='HV (часовая волатильность)'),
        ),
        migrations.AddField(
            model_name='pricel1',
            name='mv',
            field=models.DecimalField(decimal_places=10, default=0, help_text='Минутная волатильность. По умолчанию 0.', max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='MV (минутная волатильность)'),
        ),
        migrations.AddField(
            model_name='pricel1',
            name='wv',
            field=models.DecimalField(decimal_places=10, default=0, help_text='Недельная волатильность. По умолчанию 0.', max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='WV (недельная волатильность)'),
        ),
    ]
