# Generated by Django 5.2.6 on 2025-09-29 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_market', '0006_exchange_webhook_endpoint_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentProviderProfile',
        ),
    ]
