# Generated by Django 5.2.6 on 2025-09-29 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_market', '0007_delete_paymentproviderprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchange',
            name='exchange_kind',
        ),
    ]
