# Generated by Django 5.2.6 on 2025-09-29 10:45

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_market', '0008_remove_exchange_exchange_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='fee_deposit_max',
            field=models.DecimalField(decimal_places=5, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Ввод: макс. комиссия'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='fee_deposit_min',
            field=models.DecimalField(decimal_places=5, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Ввод: мин. комиссия'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='fee_deposit_percent',
            field=models.DecimalField(decimal_places=5, default=Decimal('0'), max_digits=12, verbose_name='Ввод: %'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='fee_withdraw_fixed',
            field=models.DecimalField(decimal_places=5, default=Decimal('0'), max_digits=12, verbose_name='Вывод: фикс'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='fee_withdraw_max',
            field=models.DecimalField(decimal_places=5, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Вывод: макс. комиссия'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='fee_withdraw_min',
            field=models.DecimalField(decimal_places=5, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Вывод: мин. комиссия'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='fee_withdraw_percent',
            field=models.DecimalField(decimal_places=5, default=Decimal('0'), max_digits=12, verbose_name='Вывод: %'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='futures_maker_fee',
            field=models.DecimalField(decimal_places=5, default=Decimal('0.1'), help_text='Может быть отрицательной.', max_digits=12, verbose_name='Фьючерсы: мейкер, %'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='futures_taker_fee',
            field=models.DecimalField(decimal_places=5, default=Decimal('0.1'), help_text='Может быть отрицательной.', max_digits=12, verbose_name='Фьючерсы: тейкер, %'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='provider',
            field=models.CharField(choices=[('KUCOIN', 'KuCoin'), ('WHITEBIT', 'WhiteBIT'), ('RAPIRA', 'Rapira'), ('MEXC', 'MEXC'), ('PAYPAL', 'PayPal'), ('ADVCASH', 'Advanced Cash'), ('MANUAL', 'Ручной обмен')], db_index=True, help_text='Выберите из списка: биржи, ручной обмен, платёжные системы.', max_length=20, unique=True, verbose_name='Поставщик ликвидности'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='spot_maker_fee',
            field=models.DecimalField(decimal_places=5, default=Decimal('0.1'), help_text='Может быть отрицательной.', max_digits=12, verbose_name='Спот: мейкер, %'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='spot_taker_fee',
            field=models.DecimalField(decimal_places=5, default=Decimal('0.1'), help_text='Может быть отрицательной.', max_digits=12, verbose_name='Спот: тейкер, %'),
        ),
    ]
