# Generated by Django 5.2.6 on 2025-09-29 10:51

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_market', '0009_alter_exchange_fee_deposit_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='exchange_kind',
            field=models.CharField(choices=[('CEX', 'Классическая биржа (CEX)'), ('DEX', 'Децентрализованная биржа (DEX)'), ('PSP', 'Платёжная система'), ('MANUAL', 'Ручной обмен')], db_index=True, default='CEX', help_text='CEX / DEX / PSP / MANUAL', max_length=10, verbose_name='Тип поставщика'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='fee_deposit_max',
            field=models.DecimalField(decimal_places=5, default=Decimal('0'), help_text='Неотрицательная. 0 = без максимума.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Ввод: макс. комиссия'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='fee_deposit_min',
            field=models.DecimalField(decimal_places=5, default=Decimal('0'), help_text='Неотрицательная. Применяется после расчёта % + фикс. 0 = без минимума.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Ввод: мин. комиссия'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='fee_withdraw_max',
            field=models.DecimalField(decimal_places=5, default=Decimal('0'), help_text='Неотрицательная. 0 = без максимума.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Вывод: макс. комиссия'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='fee_withdraw_min',
            field=models.DecimalField(decimal_places=5, default=Decimal('0'), help_text='Неотрицательная. Применяется после расчёта % + фикс. 0 = без минимума.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Вывод: мин. комиссия'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='provider',
            field=models.CharField(choices=[('KUCOIN', 'KuCoin'), ('WHITEBIT', 'WhiteBIT'), ('RAPIRA', 'Rapira'), ('MEXC', 'MEXC'), ('MANUAL', 'Ручной обмен'), ('PAYPAL', 'PayPal'), ('ADVCASH', 'Advanced Cash')], db_index=True, help_text='Выберите из списка: биржи, ручной обмен, платёжные системы.', max_length=20, unique=True, verbose_name='Поставщик ликвидности'),
        ),
    ]
