# Generated by Django 5.2.6 on 2025-10-03 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_market', '0013_alter_exchangeapikey_options_alter_exchange_can_send_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangeasset',
            name='api_slug',
        ),
    ]
