# Generated by Django 5.2.6 on 2025-10-03 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_market', '0014_remove_exchangeasset_api_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangeasset',
            options={'ordering': ['exchange', 'asset_code', 'chain_code'], 'verbose_name': 'Актив ПЛ', 'verbose_name_plural': 'Активы ПЛ'},
        ),
        migrations.AlterField(
            model_name='exchangeasset',
            name='AD',
            field=models.BooleanField(default=True, verbose_name='Вывод (ручной)'),
        ),
        migrations.AlterField(
            model_name='exchangeasset',
            name='AW',
            field=models.BooleanField(default=True, verbose_name='Вывод (авто)'),
        ),
        migrations.AlterField(
            model_name='exchangeasset',
            name='D',
            field=models.BooleanField(default=True, verbose_name='Ввод (ручной)'),
        ),
        migrations.AlterField(
            model_name='exchangeasset',
            name='W',
            field=models.BooleanField(default=True, verbose_name='Вывод (ручной)'),
        ),
        migrations.AlterField(
            model_name='exchangeasset',
            name='asset_code',
            field=models.CharField(db_index=True, max_length=32, verbose_name='Тикет'),
        ),
        migrations.AlterField(
            model_name='exchangeasset',
            name='asset_name',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='exchangeasset',
            name='chain_code',
            field=models.CharField(db_index=True, max_length=64, verbose_name='Сеть'),
        ),
        migrations.AlterField(
            model_name='exchangeasset',
            name='chain_display',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Сеть экран'),
        ),
        migrations.AlterField(
            model_name='exchangeasset',
            name='nominal',
            field=models.PositiveIntegerField(default=1, verbose_name='Номинал'),
        ),
    ]
