# Generated by Django 5.2.6 on 2025-10-03 14:49

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_market', '0015_alter_exchangeasset_options_alter_exchangeasset_ad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangeasset',
            name='memo_hint',
        ),
        migrations.AlterField(
            model_name='exchangeasset',
            name='AD',
            field=models.BooleanField(default=True, verbose_name='Ввод (авто)'),
        ),
        migrations.AlterField(
            model_name='exchangeasset',
            name='amount_precision',
            field=models.PositiveSmallIntegerField(default=8, verbose_name='Точность актива'),
        ),
        migrations.AlterField(
            model_name='exchangeasset',
            name='deposit_fee_fixed',
            field=models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=28, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Комиссия ввода, фикс'),
        ),
        migrations.AlterField(
            model_name='exchangeasset',
            name='deposit_fee_percent',
            field=models.DecimalField(decimal_places=5, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Комиссия ввода, %'),
        ),
        migrations.AlterField(
            model_name='exchangeasset',
            name='deposit_max',
            field=models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=28, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Макс. ввод'),
        ),
        migrations.AlterField(
            model_name='exchangeasset',
            name='deposit_max_usdt',
            field=models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=28, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Макс. ввод (в USDT)'),
        ),
        migrations.AlterField(
            model_name='exchangeasset',
            name='deposit_min',
            field=models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=28, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Мин. ввод'),
        ),
        migrations.AlterField(
            model_name='exchangeasset',
            name='deposit_min_usdt',
            field=models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=28, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Мин. ввод (в USDT)'),
        ),
        migrations.AlterField(
            model_name='exchangeasset',
            name='reserve_max',
            field=models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=28, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Макс. резерв'),
        ),
        migrations.AlterField(
            model_name='exchangeasset',
            name='reserve_min',
            field=models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=28, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Мин. резерв'),
        ),
        migrations.AlterField(
            model_name='exchangeasset',
            name='withdraw_fee_fixed',
            field=models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=28, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Комиссия вывода, фикс'),
        ),
        migrations.AlterField(
            model_name='exchangeasset',
            name='withdraw_fee_percent',
            field=models.DecimalField(decimal_places=5, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Комиссия вывода, %'),
        ),
        migrations.AlterField(
            model_name='exchangeasset',
            name='withdraw_max',
            field=models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=28, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Макс. вывод'),
        ),
        migrations.AlterField(
            model_name='exchangeasset',
            name='withdraw_max_usdt',
            field=models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=28, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Макс. вывод (в USDT)'),
        ),
        migrations.AlterField(
            model_name='exchangeasset',
            name='withdraw_min',
            field=models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=28, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Мин. вывод'),
        ),
        migrations.AlterField(
            model_name='exchangeasset',
            name='withdraw_min_usdt',
            field=models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=28, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Мин. вывод (в USDTт)'),
        ),
    ]
