# Generated by Django 5.2.6 on 2025-10-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_market', '0016_remove_exchangeasset_memo_hint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeasset',
            name='amount_precision_display',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='Точность для отображения'),
        ),
    ]
