# Generated by Django 5.2.6 on 2025-09-15 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetup',
            name='admin_session_timeout_min',
            field=models.PositiveIntegerField(default=10, help_text='Через сколько минут бездействия разлогинивать из админки. 0 — не разлогинивать по простою (сессия живёт до закрытия браузера).', verbose_name='Автовыход из админки, минут'),
        ),
        migrations.AlterField(
            model_name='sitesetup',
            name='use_https_in_meta',
            field=models.BooleanField(default=False, help_text='Если выключено — будет использоваться http <strong>Объязательно включить на проде!</strong>', verbose_name='https в canonical/OG URL'),
        ),
    ]
