# Generated by Django 5.2.6 on 2025-10-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetup',
            name='memo_required_chains',
            field=models.TextField(blank=True, default='XRP, XLM, EOS, TON, ATOM, OSMO, KAVA, LUNC, LUNA, BNB, XEM, HBAR', help_text='Через запятую. Канонические коды сетей в ВЕРХНЕМ регистре (например: XRP, TON, BNB).', verbose_name='Сети, где требуется MEMO/TAG'),
        ),
        migrations.AlterField(
            model_name='sitesetup',
            name='stablecoins',
            field=models.TextField(blank=True, default='USDT, USDC, DAI, TUSD, FDUSD, PYUSD, USDP, GUSD, EURT, EURC, FRAX, EURR, EURI, USAT, USDS, USDE', help_text='Через запятую, тикеры в верхнем регистре (например: USDT, USDC, DAI).', verbose_name='Список стейблкоинов'),
        ),
    ]
