# Generated by Django 5.2.6 on 2025-10-18 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetup',
            name='exchange_mode',
            field=models.CharField(choices=[('ALL', 'Обмен всё-на-всё'), ('WL', 'Только явно разрешённые направления')], default='ALL', help_text='ALL — все доступные активы можно менять между собой. WL — по умолчанию ничего не меняется; разрешены только направления, указанные явным образом.', max_length=3, verbose_name='Режим работы обменника'),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='price_ttl_minutes',
            field=models.PositiveIntegerField(default=0, help_text='0 — не проверять свежесть. >0 — если последняя котировка старше этого порога, актив автоматически считается временно недоступным для ввода/вывода.', verbose_name='Время жизни котировки (минуты)'),
        ),
    ]
