# Generated by Django 5.2.6 on 2025-09-22 12:33

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitoring',
            name='banner_black',
        ),
        migrations.RemoveField(
            model_name='monitoring',
            name='banner_white',
        ),
        migrations.AlterField(
            model_name='monitoring',
            name='link',
            field=models.URLField(default='https://www.bestchange.ru/', max_length=500, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='monitoring',
            name='name',
            field=models.CharField(default='Bestchange', max_length=120, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='monitoring',
            name='percent',
            field=models.DecimalField(decimal_places=8, default=Decimal('30'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Партнёрский процент'),
        ),
    ]
