# Generated by Django 5.2.6 on 2025-10-07 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetup',
            name='admin_session_timeout_min',
            field=models.PositiveIntegerField(default=20, help_text='Через сколько минут бездействия разлогинивать из админки. 0 — не разлогинивать по простою (сессия живёт до закрытия браузера).', verbose_name='Автовыход из админки, минут'),
        ),
    ]
