# Generated by Django 5.2.6 on 2025-10-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetup',
            name='fiat_name',
            field=models.TextField(blank=True, default='AED, AFN, ALL, AMD, ANG, AOA, ARS, AUD, AWG, AZN, BAM, BBD, BDT, BGN, BHD, BIF, BMD, BND, BOB, BRL, BSD, BTN, BWP, BYN, BZD, CAD, CDF, CHF, CLP, CNY, COP, CRC, CUP, CVE, CZK, DJF, DKK, DOP, DZD, EGP, ERN, ETB, EUR, FJD, FKP, GBP, GEL, GHS, GIP, GMD, GNF, GTQ, GYD, HKD, HNL, HTG, HUF, IDR, ILS, INR, IQD, IRR, ISK, JMD, JOD, JPY, KES, KGS, KHR, KMF, KPW, KRW, KWD, KYD, KZT, LAK, LBP, LKR, LRD, LSL, LYD, MAD, MDL, MGA, MKD, MMK, MNT, MOP, MRU, MUR, MVR, MWK, MXN, MYR, MZN, NAD, NGN, NIO, NOK, NPR, NZD, OMR, PAB, PEN, PGK, PHP, PKR, PLN, PYG, QAR, RON, RSD, RUB, RWF, SAR, SBD, SCR, SDG, SEK, SGD, SHP, SLE, SOS, SRD, SSP, STN, SYP, SZL, THB, TJS, TMT, TND, TOP, TRY, TTD, TWD, TZS, UAH, UGX, USD, UYU, UZS, VED, VES, VND, VUV, WST, XAF, XCD, XOF, XPF, YER, ZAR, ZMW, ZWG, UAHG, XAUT,', help_text='Через запятую. (например: EUR, USD, RUB).', verbose_name='Фиатные валюты'),
        ),
        migrations.AlterField(
            model_name='sitesetup',
            name='stablecoins',
            field=models.TextField(blank=True, default='USDT, USDC, PYUSD, FDUSD, TUSD, USDP, GUSD, DAI, USDS, USDe, RLUSD, frxUSD, FRAX, LUSD, GHO, crvUSD, sUSD, DOLA, MIM, USDD, USDM, USDV, USD0, USDH, HAY, alUSD, USX, VAI, eUSD, GRAI, USK, DJED, USDA, BOLD, USDK,EURC, EURT, EURS, EUROe, EURe, EURA, AEUR, EURI, EURR, agEUR, cEUR, jEUR, PAR,GBPT, GBPe,XSGD, XIDR, BRZ, MXNT,XCHF, VCHF, HCHF,GYEN, JPYC,ZARP,QCAD, CADC, TRYB, TAUD, AUDD, DECL, USD1, USDR', help_text='Через запятую (например: USDT, USDC, DAI).', verbose_name='Стейблкоины'),
        ),
    ]
