# Generated by Django 5.2.6 on 2025-09-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetup',
            name='enabled_languages',
            field=models.JSONField(blank=True, default=list, help_text='Какие языки показывать на сайте (переключатель, hreflang). Если пусто — будет только основной язык.'),
        ),
    ]
