# Generated by Django 5.2.6 on 2025-09-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('ru', 'Russian'), ('en', 'English')], default='ru', max_length=8, verbose_name='Язык интерфейса'),
        ),
    ]
