# Generated by Django 5.2.6 on 2025-09-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoring',
            name='clicks_total',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Кликов всего'),
        ),
        migrations.AddField(
            model_name='monitoring',
            name='last_click_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Последний клик'),
        ),
    ]
