# Generated by Django 5.2.6 on 2025-09-12 16:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0002_user_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetup',
            name='domain',
            field=models.CharField(default='swap.com', help_text='Например: example.com или localhost (без http/https).', max_length=253, validators=[django.core.validators.RegexValidator(message='Введите корректное доменное имя, например: example.com', regex='^(localhost|(?:(?!-)[A-Za-z0-9-]{1,63}(?<!-)\\.)+[A-Za-z]{2,63})$')], verbose_name='Домен (без http/https)'),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='domain_view',
            field=models.CharField(default='Swap', help_text='Название для заголовков/письма и т.п., например: "Swap".', max_length=100, verbose_name='Отображаемое имя сайта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('ru', 'Russian'), ('en', 'English')], default='ru', max_length=8, verbose_name='Язык общения'),
        ),
    ]
