# Generated by Django 5.2.6 on 2025-09-19 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0002_sitesetup_enabled_languages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesetup',
            old_name='enabled_languages',
            new_name='site_enabled_languages',
        ),
    ]
