# Generated by Django 5.2.6 on 2025-09-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0002_sitesetup_admin_session_timeout_min_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetup',
            name='ref_attribution_window_days',
            field=models.PositiveIntegerField(default=90, help_text='Срок жизни подписанной referral-cookie. Last click wins: последний клик по реферальной ссылке действует до регистрации. 0 — не ставить долгоживущую cookie (только сессия до закрытия браузера).', verbose_name='Окно атрибуции (дней)'),
        ),
        migrations.AddField(
            model_name='user',
            name='referral_first_seen_at',
            field=models.DateTimeField(blank=True, help_text='Дата и время первого визита с реферальным кодом.', null=True, verbose_name='Первый визит по партнёрской ссылке'),
        ),
        migrations.AddField(
            model_name='user',
            name='referral_signup_delay',
            field=models.DurationField(blank=True, help_text='Разница между первым визитом по реф-ссылке и моментом регистрации.', null=True, verbose_name='Задержка до регистрации'),
        ),
    ]
