# Generated by Django 5.2.6 on 2025-09-23 15:34

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0003_document_documenttranslation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttranslation',
            name='body',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Содержимое'),
        ),
    ]
