# Generated by Django 5.2.6 on 2025-09-15 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0003_sitesetup_ref_attribution_window_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetup',
            name='contact_label_clients',
            field=models.CharField(blank=True, default='', help_text='Если пусто — используется «Почта для клиентов».', max_length=120, verbose_name='Заголовок: почта для клиентов'),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='contact_label_general',
            field=models.CharField(blank=True, default='', help_text='Если пусто — используется «Почта для общих вопросов».', max_length=120, verbose_name='Заголовок: почта для общих вопросов'),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='contact_label_partners',
            field=models.CharField(blank=True, default='', help_text='Если пусто — используется «Почта для партнёров».', max_length=120, verbose_name='Заголовок: почта для партнёров'),
        ),
        migrations.AlterField(
            model_name='sitesetup',
            name='use_https_in_meta',
            field=models.BooleanField(default=False, help_text='Если выключено — будет использоваться http Объязательно включить на проде!', verbose_name='https в canonical/OG URL'),
        ),
    ]
