# Generated by Django 5.2.6 on 2025-09-12 20:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0003_sitesetup_domain_sitesetup_domain_view_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetup',
            name='robots_txt',
            field=models.TextField(blank=True, default='User-agent: *\nDisallow:\n', help_text="Текст, который будет отдан по /robots.txt. Строка 'Sitemap: https://<host>/sitemap.xml' будет добавлена автоматически.", verbose_name='Содержимое robots.txt'),
        ),
        migrations.AlterField(
            model_name='sitesetup',
            name='admin_path',
            field=models.CharField(default='admin', help_text='Например: supera-dmin', max_length=50, validators=[django.core.validators.RegexValidator(message='Разрешены только маленькие латинские буквы, цифры и дефис', regex='^[a-z0-9-]+$')], verbose_name='Путь к админке'),
        ),
    ]
