# Generated by Django 5.2.6 on 2025-09-12 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0004_sitesetup_robots_txt_alter_sitesetup_admin_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
    ]
