# Generated by Django 5.2.6 on 2025-09-23 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0004_alter_documenttranslation_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='documenttranslation',
            name='seo_description',
        ),
        migrations.RemoveField(
            model_name='documenttranslation',
            name='seo_title',
        ),
    ]
