# Generated by Django 5.2.6 on 2025-09-16 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0004_sitesetup_contact_label_clients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetup',
            name='csp_extra_connect_src',
            field=models.TextField(blank=True, default='', help_text='Например: https://mc.yandex.ru https://api.example.com.', verbose_name='CSP: дополнительные источники connect-src'),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='csp_extra_font_src',
            field=models.TextField(blank=True, default='', help_text='Например: https://fonts.gstatic.com data:.', verbose_name='CSP: дополнительные источники font-src'),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='csp_extra_frame_src',
            field=models.TextField(blank=True, default='', help_text='Например: https://www.youtube.com https://player.vimeo.com.', verbose_name='CSP: дополнительные источники frame-src'),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='csp_extra_img_src',
            field=models.TextField(blank=True, default='', help_text='Например: https://mc.yandex.ru data: blob:.', verbose_name='CSP: дополнительные источники img-src'),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='csp_extra_script_src',
            field=models.TextField(blank=True, default='', help_text="Через запятую или пробел: например https://mc.yandex.ru https://code.jivo.ru https://www.googletagmanager.com 'unsafe-eval' (не рекомендуется).", verbose_name='CSP: дополнительные источники script-src'),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='csp_extra_style_src',
            field=models.TextField(blank=True, default='', help_text='Например: https://fonts.googleapis.com.', verbose_name='CSP: дополнительные источники style-src'),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='csp_report_only',
            field=models.BooleanField(default=False, help_text="Если включено — политика будет в режиме отчётов (не блокирует), заголовок 'Content-Security-Policy-Report-Only'.", verbose_name='CSP: режим Report-Only'),
        ),
        migrations.AlterField(
            model_name='sitesetup',
            name='robots_txt',
            field=models.TextField(blank=True, default='User-agent: *\nDisallow:\n', help_text='Текст, который будет отдан по /robots.txt. Строка Sitemap: https://HOST/sitemap.xml позже будет добавлена автоматически.', verbose_name='Содержимое robots.txt'),
        ),
        migrations.AlterField(
            model_name='sitesetup',
            name='telegram_chat_id',
            field=models.CharField(blank=True, default='', help_text='ID  канала/чата, куда слать служебные уведомления. Чтобы узнать ID запустите бота: @username_to_id_bot', max_length=64, verbose_name='Telegram Chat/Channel ID'),
        ),
    ]
