# Generated by Django 5.2.6 on 2025-09-17 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0005_sitesetup_csp_extra_connect_src_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetup',
            name='block_indexing',
            field=models.BooleanField(default=False, help_text="Если включено, robots.txt будет отдавать 'Disallow: /', а во всех ответах будет заголовок 'X-Robots-Tag: noindex, nofollow'", verbose_name='Запретить индексацию сайта'),
        ),
        migrations.AlterField(
            model_name='sitesetup',
            name='ref_attribution_window_days',
            field=models.PositiveIntegerField(default=90, help_text='Срок жизни подписанной referral-cookie. Last click wins: последний клик по реферальной ссылке действует до регистрации. 0 — не ставить долгоживущую cookie (только сессия до закрытия браузера).', verbose_name='Срок хранения куки (дней)'),
        ),
    ]
