# Generated by Django 5.2.6 on 2025-09-23 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0005_remove_document_is_published_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='created_at',
        ),
    ]
