# Generated by Django 5.2.6 on 2025-09-12 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0005_sitesetup_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetup',
            name='block_indexing',
            field=models.BooleanField(default=False, help_text="Если включено, robots.txt будет отдавать 'Disallow: /', а во всех ответах будет заголовок 'X-Robots-Tag: noindex, nofollow'", verbose_name='Запретить индексацию всего сайта'),
        ),
    ]
