# Generated by Django 5.2.6 on 2025-09-14 12:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0006_sitesetup_block_indexing'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetup',
            name='close_time_fri',
            field=models.TimeField(default='19:00', verbose_name='Пятница: конец (UTC)'),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='close_time_mon',
            field=models.TimeField(default='19:00', verbose_name='Понедельник: конец (UTC)'),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='close_time_sat',
            field=models.TimeField(default='17:00', verbose_name='Суббота: конец (UTC)'),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='close_time_sun',
            field=models.TimeField(default='17:00', verbose_name='Воскресенье: конец (UTC)'),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='close_time_thu',
            field=models.TimeField(default='19:00', verbose_name='Четверг: конец (UTC)'),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='close_time_tue',
            field=models.TimeField(default='19:00', verbose_name='Вторник: конец (UTC)'),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='close_time_wed',
            field=models.TimeField(default='19:00', verbose_name='Среда: конец (UTC)'),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='contact_email_clients',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Почта для клиентов'),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='contact_email_general',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Почта для общих вопросов'),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='contact_email_partners',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Почта для партнёров'),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='contact_telegram',
            field=models.CharField(blank=True, default='', help_text='Ссылка t.me/... или @username', max_length=255, verbose_name='Telegram для связи'),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='email_from',
            field=models.EmailField(blank=True, help_text='Например: no-reply@swap.com', max_length=254, verbose_name='E-mail отправителя (FROM)'),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='email_host',
            field=models.CharField(blank=True, default='smtp.yourprovider.com', max_length=255, verbose_name='SMTP host'),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='email_host_password',
            field=models.CharField(blank=True, max_length=255, verbose_name='SMTP password'),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='email_host_user',
            field=models.CharField(blank=True, max_length=255, verbose_name='SMTP user'),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='email_port',
            field=models.PositiveIntegerField(default=587, verbose_name='SMTP port'),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='email_use_ssl',
            field=models.BooleanField(default=False, verbose_name='Использовать SSL'),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='email_use_tls',
            field=models.BooleanField(default=True, verbose_name='Использовать TLS'),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='favicon',
            field=models.ImageField(blank=True, help_text='PNG/ICO 32×32 или 48×48.', null=True, upload_to='branding/', verbose_name='Favicon'),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='fee_percent',
            field=models.DecimalField(decimal_places=2, default=0.5, help_text='Процент с каждой сделки (0–100).', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Комиссия обменника, %'),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='head_inject_html',
            field=models.TextField(blank=True, help_text='Счётчики/метрики и т.п. Вставляется как есть на всех страницах.', verbose_name='HTML-код для вставки в <head>'),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='logo',
            field=models.ImageField(blank=True, help_text='PNG/SVG; будет использоваться в шапке/мета.', null=True, upload_to='branding/', verbose_name='Логотип'),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='main_h1',
            field=models.CharField(default='Мгновенный обмен криптовалют онлайн', max_length=200, verbose_name='H1 на главной'),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='main_subtitle',
            field=models.TextField(blank=True, default='Обменивайте Bitcoin, Ethereum и стейблкоины быстро, безопасно и по честному курсу.', verbose_name='Подзаголовок на главной'),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='maintenance_mode',
            field=models.BooleanField(default=False, help_text='Если включено — пользователи увидят страницу техработ. По умолчанию выключено.', verbose_name='Технические работы (сайт недоступен)'),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='open_time_fri',
            field=models.TimeField(default='07:00', verbose_name='Пятница: начало (UTC)'),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='open_time_mon',
            field=models.TimeField(default='07:00', help_text='Время хранится в формате UTC. Значения по умолчанию соответствуют графику по Москве (пн–пт 10:00–22:00, сб–вс 12:00–20:00). При изменении учитывайте разницу с МСК (UTC+3).', verbose_name='Понедельник: начало (UTC)'),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='open_time_sat',
            field=models.TimeField(default='09:00', verbose_name='Суббота: начало (UTC)'),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='open_time_sun',
            field=models.TimeField(default='09:00', verbose_name='Воскресенье: начало (UTC)'),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='open_time_thu',
            field=models.TimeField(default='07:00', verbose_name='Четверг: начало (UTC)'),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='open_time_tue',
            field=models.TimeField(default='07:00', verbose_name='Вторник: начало (UTC)'),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='open_time_wed',
            field=models.TimeField(default='07:00', verbose_name='Среда: начало (UTC)'),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='seo_default_description',
            field=models.TextField(blank=True, default='Онлайн-обменник криптовалют. Мгновенные сделки, прозрачные курсы, низкая комиссия. Поддержка Bitcoin, Ethereum и популярных стейблкоинов (USDT, USDC, DAI и др.).', help_text='Используется как базовое описание, если страница не переопределяет его.', verbose_name='SEO: описание по умолчанию (meta description)'),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='seo_default_keywords',
            field=models.TextField(blank=True, default='обменник, криптовалюта, обмен криптовалют, bitcoin, ethereum, usdt, usdc, dai, обмен онлайн', help_text='Опционально. Может не использоваться поисковиками, но полезно для некоторых интеграций.', verbose_name='SEO: ключевые слова по умолчанию (meta keywords)'),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='seo_default_title',
            field=models.CharField(blank=True, default='Swap — быстрый и безопасный обмен криптовалют и стейблкоинов онлайн', help_text='Используется как базовый <title>, если страница не переопределяет его.', max_length=255, verbose_name='SEO: заголовок по умолчанию (title)'),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='social_dzen',
            field=models.URLField(blank=True, default='', verbose_name='Дзен'),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='social_instagram',
            field=models.URLField(blank=True, default='', verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='social_rutube',
            field=models.URLField(blank=True, default='', verbose_name='RuTube'),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='social_tg',
            field=models.URLField(blank=True, default='', verbose_name='Telegram-канал'),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='social_twitter',
            field=models.URLField(blank=True, default='', verbose_name='Twitter/X'),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='social_vk',
            field=models.URLField(blank=True, default='', verbose_name='VK'),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='social_youtube',
            field=models.URLField(blank=True, default='', verbose_name='YouTube'),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='stablecoins',
            field=models.TextField(blank=True, default='USDT, USDC, DAI, TUSD, FDUSD, PYUSD, USDP, GUSD, EURT, EURC, FRAX', help_text='Через запятую, тикеры в верхнем регистре (например: USDT, USDC, DAI).', verbose_name='Список стейблкоинов'),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='telegram_bot_token',
            field=models.CharField(blank=True, help_text='Токен бота для уведомлений (хранится как есть).', max_length=255, verbose_name='Telegram Bot Token'),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='ID или @username канала/чата, куда слать служебные уведомления.', max_length=64, verbose_name='Telegram Chat/Channel ID'),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='xml_export_path',
            field=models.CharField(default='xml_export', help_text='Будущая точка выдачи XML, например «xml_export» → /xml_export', max_length=64, validators=[django.core.validators.RegexValidator(message="Разрешены строчные латинские буквы, цифры, '-', '_' и '/'. Без ведущего слеша.", regex='^[a-z0-9/_-]+$')], verbose_name='Путь для XML-выгрузки'),
        ),
    ]
