# Generated by Django 5.2.6 on 2025-09-23 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0006_remove_document_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='show_in_footer',
        ),
        migrations.RemoveField(
            model_name='document',
            name='show_in_menu',
        ),
    ]
