# Generated by Django 5.2.6 on 2025-09-17 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0006_alter_sitesetup_block_indexing_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlocklistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['email'], name='app_main_bl_email_48261d_idx'), models.Index(fields=['ip_address'], name='app_main_bl_ip_addr_760594_idx'), models.Index(fields=['is_active'], name='app_main_bl_is_acti_582ec6_idx')],
            },
        ),
    ]
