# Generated by Django 5.2.6 on 2025-09-23 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0007_remove_document_show_in_footer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
        migrations.RemoveField(
            model_name='document',
            name='order',
        ),
    ]
