# Generated by Django 5.2.6 on 2025-09-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0008_alter_document_options_remove_document_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='show_in_menu',
            field=models.BooleanField(default=True, verbose_name='Показывать на сайте'),
        ),
    ]
