# Generated by Django 5.2.6 on 2025-09-23 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0009_document_show_in_menu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='show_in_menu',
            new_name='show_in_site',
        ),
    ]
