# Generated by Django 5.2.6 on 2025-09-22 12:17

import app_library.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannerAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('theme', models.CharField(choices=[('dark', 'Тёмный'), ('light', 'Светлый')], default='dark', max_length=5, verbose_name='Тема')),
                ('file', models.FileField(upload_to='partners/banners/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'svg']), app_library.models.validate_banner_filesize], verbose_name='Файл баннера')),
                ('size_bytes', models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Размер файла (байт)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Библиотека баннеров',
                'ordering': ('name',),
            },
        ),
    ]
