# Generated by Django 5.2.6 on 2025-09-24 21:26

import app_library.models
import django.core.validators
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannerAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('theme', models.CharField(choices=[('dark', 'Тёмный'), ('light', 'Светлый')], default='dark', max_length=5, verbose_name='Тема')),
                ('file', models.FileField(upload_to='partners/banners/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'svg']), app_library.models.validate_banner_filesize], verbose_name='Файл баннера')),
                ('size_bytes', models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Размер файла (байт)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Библиотека баннеров',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('rules', 'Правила обмена'), ('privacy', 'Политика конфиденциальности'), ('tos', 'Пользовательское соглашение'), ('disclaimer', 'Риски / Отказ от ответственности'), ('gov_requests', 'Руководство по запросам от компетентных органов'), ('aml_kyc', 'Политика AML / KYC'), ('faq', 'Вопросы и ответы (FAQ)')], max_length=32, unique=True, verbose_name='Тип')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок (RU)')),
                ('body', django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', verbose_name='Текст (RU)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Шаблон документа',
                'verbose_name_plural': 'Шаблоны документов',
                'ordering': ('kind',),
            },
        ),
    ]
