# Generated by Django 5.2.6 on 2025-09-24 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_library', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documenttemplate',
            name='title',
        ),
    ]
