# Generated by Django 5.2.6 on 2025-09-24 07:11

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('rules', 'Правила обмена'), ('privacy', 'Политика конфиденциальности'), ('tos', 'Пользовательское соглашение'), ('disclaimer', 'Риски / Отказ от ответственности'), ('gov_requests', 'Руководство по запросам от компетентных органов'), ('aml_kyc', 'Политика AML / KYC'), ('faq', 'Вопросы и ответы (FAQ)')], max_length=32, unique=True, verbose_name='Тип')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок (RU)')),
                ('body', django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', verbose_name='Текст (RU)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Шаблон документа',
                'verbose_name_plural': 'Шаблоны документов',
                'ordering': ('kind',),
            },
        ),
    ]
